services: views
  - type: web
    name: youtube-views-bot
    env: python
    repo: https://github.com/Schumynet/YouTubeViews-
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python youtube.py 30000 urls.txt 800 3600
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"